image: Visual Studio 2017

environment:
  matrix:
    - solution_name: 1_week/1_task/1_task.sln
    - solution_name: 1_week/3_task/3_task.sln
    - solution_name: 1_week/4_task/4_task.sln
    - solution_name: 1_week/5_task/5_task.sln

before_build:
  - nuget restore %solution_name%

build_script:
  - msbuild %solution_name%

test_script:
  - vstest.console /logger:Appveyor %solution_name%
